### ISSUE TITLE
Google maps error

### ISSUE THREAD

**Issue by benmelz** [umts/incidents#367]
> Good afternoon, Transit I.T.;
>  
> I was recently completing an accident report for a driver and when I clicked to place the marker pin on the map, I saw the red error message (displayed on the included screenshot just above the map), and wanted to make you aware.
>  
> Thanks,
> -Jamin

![image](https://github.com/umts/incidents/assets/8195530/b1064ac9-034b-4b9d-8539-e1c6c0925dd6)

**Comment by frothedoatmilk** [comment]
So, aside from the "our API key is busted," this seems like poor form design? The error is non-descriptive because it's the same error regardless of:

- Did the API load?
- Does the lat/long make sense?
- Did the geocode fail?

It'll also throw up that error if no coordinates were entered (even though it also defaults to the PVTA homebase?). So I'm going to make the errors a little bit more descriptive.

**Comment by benmelz** [comment]
If those are easy, sure, but if we're going to be writing a lot of custom logic (which I would _expect_ to be the case for at least "does the lat/long make sense?") I don't think it's worth our time.

**Comment by frothedoatmilk** [comment]
It can be a lot more verbose than "mmm google error" without insane logic, even putting down "Error processing address from coordinates" or "Google API failed to load" would be more helpful (those are the two current branches where errors get caught)

**Comment by frothedoatmilk** [comment]
As @benmelz discovered this issue has to do with how the API key has been set up, rather than an issue we can identify on our end (so far).
