### ISSUE TITLE
Disable incident report button while submitting

### ISSUE THREAD

**Issue by benmelz** [umts/incidents#369]
> Good morning, Transit IT;
> 
> I was wondering if some/all of the following modifications could be made to the incident reports system?
> 
> A more visible progress bar/loading screen when creating a new incident report.  Currently, we get at least one, if not two, accidental duplicate incident reports as the drivers click the new incident report button thinking that the website is not chugging along creating a new report.
> Google Maps does not seem to be positioning pins on the map when addresses are entered into the address boxes; is it possible to bring back that functionality?  No biggie if not.
> 
> Thanks,
> -Jamin

The google maps part is #367, if I'm not mistaken

**Comment by werebus** [comment]
I think there was a misunderstanding in how this issue was closed. The "new" action is a `GET` request. A driver could click it a thousand times and not make any changes to the database. I'm pretty sure Jamin meant the submit button on the form, right?

(I'm here commenting because I was thinking about removing the functionality added in #370)
